 //Trazer as casas depois da virgula
// const numero = 198.9999;

// console.log(numero.toFixed(2));

//-------------------------------------------------------------------------------------------------------------------------------------
//Conversao:
const numUm = "123";
const numDois = "54545.48";

//parseINT
console.log(numUm);

console.log(parseInt(numUm));

//parseFloat
console.log(parseFloat(numDois));


