// const nome = "Carlos Roque";

// //Deixa a Letra Maiuscula
// console.log(nome.toUpperCase());

// //Deixa a letra Minuscula
// console.log(nome.toLowerCase());

//--------------------------------------------------------------------------------------------------------------------------------
const frase = "Hoje e um bom dia para estudar JavaScript"

console.log(frase.includes("JavaScript")); //true
console.log(frase.includes("Phyton")); //False

//--------------------------------------------------------------------------------------------------------------------------------

const texto = "Ola, Maria!";
const novoTexto = texto.replace("Maria", "Joao");

console.log(novoTexto); //Imprimira: "Ola, Joao!"





